package(default_visibility = ["//visibility:public"])

java_library(
    name = "soy",
    srcs = glob(["tech/brownbear/soy/*.java"]),
    deps = [
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:commons_logging_commons_logging",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_template_soy",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_code_findbugs_jsr305",
    ],
)